version: 2

models:
  - name: fact_spotify_rankings_report
    description: >
      Final reporting model used in Looker Studio to analyze global vs. local song popularity and track ranking trends over time.
      Combines fact_spotify_rankings and dim_songs.

    columns:
      - name: spotify_id
        description: "Unique identifier of the song from Spotify."
        tests:
          - not_null

      - name: song_name
        description: "Name of the song as listed in dim_songs."
        tests:
          - not_null

      - name: country_id
        description: "ISO country code (or 'Global' if it's the global Top 50 chart)."
        tests:
          - not_null

      - name: date_id
        description: "The date the ranking was captured."
        tests:
          - not_null

      - name: daily_rank
        description: "Position of the song in the Top 50 on that day."
        tests:
          - not_null

      - name: popularity
        description: "Popularity score assigned by Spotify."
        tests: []